add_newline = true
command_timeout = 1000

[time]
disabled = true

[battery]
disabled = false

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 40
style = "bold yellow"

[[battery.display]]
threshold = 60
style = "bold green"

[[battery.display]]
threshold = 80
style = "bold white"

[docker_context]
disabled = false

[status]
disabled = false
map_symbol = true

[shell]
disabled = false

[kubernetes]
disabled = false
format = 'on [⛵ $context \($namespace\)](cyan bold) '
